feat : address and payment integration
mikesch803/react-fit-store pull request #21
Opened 2022-06-20 09:46 UTC by mikesch803

1. add address ( create, delete )
2. add razorpay intregation

2022-06-20 10:27 UTC, nayyyhaa requested changes
Nice work in integrating address management + Razorpay! 💯 

One thing I find is that after placing a successful order -> cart will get cleared -> if I add another new product -> old cleared item will still be there in the cart. Try to check this flow.

2022-06-20 10:27 UTC, nayyyhaa commented on src/components/cart-price-card/CartPriceCard.jsx
> +        resovle(false);
typo here. it should be 'resolve'

2022-06-20 10:27 UTC, nayyyhaa commented on src/hooks/useToast.js
> +    // console.log(msg, type, ' working')
Can remove console.logs

2022-06-20 10:27 UTC, nayyyhaa commented on src/pages/profile-page/Profile.jsx
> +  useTitle("Profile");
appreciation: use of custom hooks to change title

2022-06-21 06:06 UTC, mikesch803 commented on src/components/cart-price-card/CartPriceCard.jsx
> +        resovle(false);
thanks for pointing out

2022-06-21 06:07 UTC, mikesch803 commented on src/hooks/useToast.js
> +    // console.log(msg, type, ' working')
thanks, forget to remove hook

2022-06-21 06:08 UTC, mikesch803 commented
> Nice work in integrating address management + Razorpay! 💯
> 
> One thing I find is that after placing a successful order -> cart will get cleared -> if I add another new product -> old cleared item will still be there in the cart. Try to check this flow.

Thanks neha, I fixed the following bug

2022-06-21 13:31 UTC, dev-prabhat approved these changes
Just work on the suggestion given 
Good to merge

2022-06-22 02:49 UTC, abhisheksahani-nova approved these changes
Looks good nothing much to suggest

2022-06-22 05:13 UTC, nayyyhaa approved these changes
Yes, now it's working fine. Awesome!

2022-06-22 05:14 UTC, merged